### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by Yakumo-Yukari** [ruislan/ktap#8]
![2023-09-22 091416](https://github.com/ruislan/ktap/assets/12076232/7373b586-61ff-49e0-b23d-c894f79ec216)

![2023-09-22 090854](https://github.com/ruislan/ktap/assets/12076232/eb95b64a-a2fb-4a4c-a49a-593576fc161b)

这个位置的管理按钮应该在没有相关权限的时候不可见 

不知道是不是还没实现的关系

**Comment by ruislan** [comment]
已经改了，我找时间更新一下demo。
